### ISSUE TITLE
Bounding box position shifted

### ISSUE THREAD

**Issue by naveenvj25** [rooneysh/Labelme2YOLO#15]
Hello,
I used your logic in converting labelme json file to yolo text file. The dimension of the box is not much changed but the position seems to be shifted from the actual locations. Hence the yolo model is not able to detect the actual object in the object detection task

**Comment by wzm2256** [comment]
Hi can you provide a concrete example?

**Comment by naveenvj25** [comment]
Hello, Actually it was a mistake on my end in calculating the center points in the conversion code. I corrected the same, and now it's working well.

**Comment by wzm2256** [comment]
Oh I see. Thanks for your reply. Please close this issue.
